### ISSUE TITLE
I3D features dowload

### ISSUE THREAD

**Issue by lts427** [OpenGVLab/EgoExoLearn#1]
Interesting work! I would like to know when we could download the I3D features for use. Thank you.

**Comment by hyf015** [comment]
Hi, thank you for your interest! We have already provided the I3D features. 
[RGB](https://drive.google.com/file/d/1YH0tJLy4YL0_VOW56rQSf-LDIhHkxJhl/view?usp=drive_link)
[RGB_gaze_cropped](https://drive.google.com/file/d/1-MCjVrPC25yXgxb5eu6Sgx8HDMQb0ZMa/view?usp=drive_link)
