### ISSUE TITLE
Where is Option 2 and more?

### ISSUE THREAD

**Issue by NirViaje** [OpenGVLab/EgoExoLearn#2]
Since Option 1 is here
- https://github.com/OpenGVLab/EgoExoLearn#option-1-google-drive-links

**Comment by hyf015** [comment]
We are figuring out a BaiDuYun option, please stay tuned.

**Comment by hyf015** [comment]
> Since Option 1 is here
> 
> * https://github.com/OpenGVLab/EgoExoLearn#option-1-google-drive-links

Hi, thanks for your patience. We have updated the BaiDuYun link to access our data, feel free to have a try!
If there are other suggestions on which platform is easy to access, please don't hesitate to comment here.
