### ISSUE TITLE
Download Copyright

### ISSUE THREAD

**Issue by lts427** [OpenGVLab/EgoExoLearn#3]
Hi! When clicking the google-drive link for dowloading extracted features, I found that we did not have the access copyright. I woud appreciate it if you could check this issue. Thank you.

https://drive.google.com/file/u/0/d/1YH0tJLy4YL0_VOW56rQSf-LDIhHkxJhl/view?usp=drive_link&pli=1

**Comment by hyf015** [comment]
Hi, thank you for your interest in our dataset!

There is no copyright in the google drive link. If you do not have access to the file, you can simply click "request access" and we will give your account download access.
