### ISSUE TITLE
Question about temporal action segmentation annotations

### ISSUE THREAD

**Issue by Yuhan-Shen** [OpenGVLab/EgoExoLearn#4]
Hello,

I noticed there are several .txt files under the [temporal_action_segmentation_benchmark](https://github.com/OpenGVLab/EgoExoLearn/tree/main/temporal_action_segmentation_benchmark/tas_annotation/gts_fps25) directory. Are these files the per-frame labels of the actions in the videos? If so, they seem to contain label indexes. Could you provide the actual action names that correspond to these indexes?

Thank you!

**Comment by hyf015** [comment]
Hi,
Thank you for your interest in our dataset! Sorry that I did not see this issue in time.
We have uploaded this correspondence at https://github.com/OpenGVLab/EgoExoLearn/tree/main/temporal_action_segmentation_benchmark/tas_annotation
Please take a look!
