### ISSUE TITLE
Question About Annotations

### ISSUE THREAD

**Issue by 594zyc** [OpenGVLab/EgoExoLearn#6]
Hi, 

Thanks for releasing such a great dataset!  I have two questions about the anntations:
1. Is it possible to get the type of the task as well as the instructional manual (e.g. the recipe for cooking) for each video? 
2. Is there a plan to also release the coarse-level language annotations as mentioned in the paper?

Thanks

**Comment by hyf015** [comment]
Hi,

Thank you for your interest in our dataset! Here are the responses:

1. We will release the type of the task and update the video meta within this week. For the instructional manual, there is in fact no instructional manual but only the exo-view videos as instructions.
2. Yes, the coarse-level annotations will be released within the next week.

**Comment by 594zyc** [comment]
Thanks for the prompt response. It's great to hear that the annotations will be released soon! 

If the task type is associated with a video, can we use its example procedure listed in Table S10 from the supplementary material as the instructional manual? Is there much deviation between that and the actual procedure carried out by the task performers?

**Comment by hyf015** [comment]
It is okay to use Table S10 for Tasks 1-6, for tasks 7 and 8 there may be many repetition steps however now shown in the table.

**Comment by 594zyc** [comment]
Thanks for the information!

**Comment by hyf015** [comment]
> Thanks for the information!

Hi, the task for each video has just been updated in the metafile. Feel free to re-open this issue if you have further questions!
